version: "3.8"
services:
  react_card_container:
    build: ./card-react
    # build:
    #   context: ./card-react
    #   dockerfile: Dockerfile

    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
